import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { AppComponent } from 'src/app/app.component';
import { TasksComponent } from 'src/app/components/tasks/tasks.component';
import {FormsModule, ReactiveFormsModule} from '@angular/forms';
import {RouterModule} from '@angular/router';
import {HttpClient, HttpClientModule} from '@angular/common/http';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { MatSliderModule } from '@angular/material/slider';
import { LoginComponent } from 'src/app/components/login/login.component';
import {MatCardModule} from '@angular/material/card';
import {MatTabsModule} from '@angular/material/tabs';
import {MatFormFieldModule} from '@angular/material/form-field';
import {MatIconModule} from '@angular/material/icon';
import {MatCheckboxModule} from '@angular/material/checkbox';
import { AppRoutingModule } from 'src/app/app-routing.module';
import {MatInputModule} from '@angular/material/input';
import {MatButtonModule} from '@angular/material/button';
import {MatToolbarModule} from '@angular/material/toolbar';
import {MatExpansionModule} from '@angular/material/expansion';
import { AmplifyService, AmplifyAngularModule } from 'aws-amplify-angular';
import { NewpasswordComponent } from 'src/app/components/dialog/newpassword/newpassword.component';
import {MatDialogModule} from '@angular/material/dialog';
import { SubtaskComponent } from 'src/app/components/dialog/subtask/subtask.component';
import {MatProgressSpinnerModule} from '@angular/material/progress-spinner';
import {MatPaginatorModule} from '@angular/material/paginator';
import {MatSidenavModule} from '@angular/material/sidenav';
import { NavComponent } from 'src/app/components/nav/nav.component';
import { LayoutModule } from '@angular/cdk/layout';
import { MatListModule } from '@angular/material/list';
import { VersionComponent } from 'src/app/components/dialog/version/version.component';
import { ForgotComponent } from 'src/app/components/dialog/forgot/forgot.component';
import {MatMenuModule} from '@angular/material/menu';
import {MatDatepickerModule} from '@angular/material/datepicker';
import {MatNativeDateModule} from '@angular/material/core';
import { SubtaskDetailsComponent } from 'src/app/components/dialog/subtask-details/subtask-details.component';
import {MatSortModule} from '@angular/material/sort';
import {MatSnackBarModule} from '@angular/material/snack-bar';
import { AutoGeneratedComponent } from 'src/app/auto-generated/auto-generated.component';
import {EditTaskComponent} from '@src/app/components/dialog/edit-task/edit-task.component';
import {MatTooltipModule} from '@angular/material/tooltip';
import {MatStepperModule} from '@angular/material/stepper';
import {MatAutocompleteModule} from '@angular/material/autocomplete';


@NgModule({
  declarations: [
    AppComponent,
    TasksComponent,
    LoginComponent,
    NewpasswordComponent,
    SubtaskComponent,
    NavComponent,
    VersionComponent,
    ForgotComponent,
    SubtaskDetailsComponent,
    AutoGeneratedComponent,
    EditTaskComponent
  ],
  entryComponents: [NewpasswordComponent],
  imports: [
    BrowserModule,
    FormsModule,
    RouterModule,
    AppRoutingModule,
    HttpClientModule,
    BrowserAnimationsModule,
    MatSliderModule,
    MatCardModule,
    MatTabsModule,
    MatFormFieldModule,
    MatIconModule,
    MatCheckboxModule,
    MatInputModule,
    MatButtonModule,
    MatToolbarModule,
    MatExpansionModule,
    AmplifyAngularModule,
    MatDialogModule,
    MatProgressSpinnerModule,
    MatPaginatorModule,
    MatSidenavModule,
    LayoutModule,
    MatListModule,
    MatMenuModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatSortModule,
    MatSnackBarModule,
    ReactiveFormsModule,
    MatTooltipModule,
    MatStepperModule,
    MatAutocompleteModule
  ],
  providers: [HttpClient, AmplifyService],
  bootstrap: [AppComponent]

})
export class AppModule { }
