/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:ede04a19-d050-4e89-910b-927df150c09e",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_JQy9YBUJg",
    "aws_user_pools_web_client_id": "13fbvqm3f0032tnpqd2cr68jbc",
    "oauth": {}
};


export default awsmobile;
